### ISSUE TITLE
MKL ilp64

### ISSUE THREAD

**Issue by papadop** [openmeeg/openmeeg#252]
On 64 bits architectures it is possible to configure MKL to work with the ilp64 mode (long ints instead of ints). This mostly works, but there are some errors in tests that should be easy to correct:
The following tests FAILED:
	  1 - OpenMEEGMathsTest-vector (SEGFAULT)
	  2 - OpenMEEGMathsTest-full (SEGFAULT)
	 13 - CM1-0-Head1 (SEGFAULT)
This would allow computations with matrices bigger than 2^31-1 (2GB) elements.

**Comment by papadop** [comment]
To reproduce the build:
cmake -DBLASLAPACK_IMPLEMENTATION=MKL -DMKL_USE_interface=ilp64 ~/src/Git/OpenMEEG-NG/

**Comment by massich** [comment]
I think this is solved by #268

**Comment by agramfort** [comment]
no it's not fixed. Currently we fix it to lp64 with:

```
set(MKL_USE_interface "lp64" CACHE STRING "for Intel(R)64 compatible arch: ilp64/lp64 or for ia32 arch: cdecl/stdcall")
```

if you replace lp64 by ilp64 you'll have the segfaults
